### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by engilyin** [dj0001/Motion-Photo-Viewer#1]
Could you please add also the sound into the video?
Thanks

**Comment by dj0001** [comment]
it should work with sound,
but most motion photos have no sound.
"Motion Photos" from the Google Camera app does not currently support audio.

Please post a motion photo with  sound.

**Comment by engilyin** [comment]
I can hear the audio right on my Google Pixel 2 XL device but I just see sound disabled on the Motion-Photo-Viewer video player.
And it is impossible to turn on the sound on the player.

**Comment by engilyin** [comment]
Sorry my bad, There are different video files. That ones indeed are without the sound. Closing.
My apologies.
